version: '3'

x-environment: &shared-env
  SMTP_FROM: "chensy0618@gmail.com"
  SMTP_TO: "chensy0618@gmail.com,khizar1248@gmail.com"
  SMTP_USER: "chensy0618@gmail.com"
  SMTP_PASS: "zqvevghkpkrxuwlo"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"

networks:
  honeynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1

services:
  cowrie-appliances:
    build:
      context: ./appliances/cowrie/
      dockerfile: docker/Dockerfile
    networks:
      honeynet:
        ipv4_address: 192.168.100.10
    ports:
      - "5900:22"
    volumes:
      - cowrie-appliances-etc:/cowrie/cowrie-git/etc
      - cowrie-appliances-var:/cowrie/cowrie-git/var

    environment:
      <<: *shared-env

  cowrie-lighting:
    build:
      context: ./lighting/cowrie/
      dockerfile: docker/Dockerfile
    networks:
      honeynet:
        ipv4_address: 192.168.100.20
    ports:
      - "554:22"
    volumes:
      - cowrie-lighting-etc:/cowrie/cowrie-git/etc
      - cowrie-lighting-var:/cowrie/cowrie-git/var

    environment:
      <<: *shared-env

  cowrie-thermostat:
    build:
      context: ./thermostat/cowrie/
      dockerfile: docker/Dockerfile
    networks:
      honeynet:
        ipv4_address: 192.168.100.30
    ports:
      - "5000:22"
    volumes:
      - cowrie-thermostat-etc:/cowrie/cowrie-git/etc
      - cowrie-thermostat-var:/cowrie/cowrie-git/var

    environment:
      <<: *shared-env

  cowrie-diagnostics:
    build:
      context: ./diagnostics/cowrie/
      dockerfile: docker/Dockerfile
    networks:
      honeynet:
        ipv4_address: 192.168.100.100
    ports:
      - "23:23"
    volumes:
      - cowrie-diagnostics-etc:/cowrie/cowrie-git/etc
      - cowrie-diagnostics-var:/cowrie/cowrie-git/var

    environment:
      <<: *shared-env

  # miniprint:
  #   build:
  #     context: ./miniprint
  #     dockerfile: Dockerfile
  #   read_only: true
  #   restart: always
  #   ports:
  #     - "9100:9100"
  #   volumes:
  #     - ./log/:/app/log/
  #     - ./uploads/:/app/uploads/
  #   networks:
  #     honeynet:
  #       ipv4_address: 192.168.100.150

volumes:
  cowrie-appliances-etc:
  cowrie-appliances-var:
  cowrie-lighting-etc:
  cowrie-lighting-var:
  cowrie-thermostat-etc:
  cowrie-thermostat-var:
  cowrie-diagnostics-etc:
  cowrie-diagnostics-var:
