language: python
matrix:
    include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7-dev'
cache: pip
install: 
- pip install -r requirements.txt
script:
- pytest ./test_printer.py 
notifications:
    email: false