version: "3.8"

networks:
  honeypots_local:

services:
  ftp_honeypot:
    build: .
    container_name: ftp_honeypot
    stdin_open: true
    tty: true
    restart: always
    tmpfs:
      - /tmp:uid=2000,gid=2000
    networks:
      - honeypots_local
    ports:
      - "21:21"
      - "30000-30050:30000-30050"
    read_only: true
    volumes:
      - $HOME/tpotce/data/honeypots/log:/var/log/honeypots
