---
version: '3'

volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
    environment:
          SMTP_FROM: "chensy0618@gmail.com"
          SMTP_TO: "chensy0618@gmail.com"
          SMTP_USER: "chensy0618@gmail.com"
          SMTP_PASS: "zqvevghkpkrxuwlo"
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"